import { Box, Button } from '@mui/material'
import Head from 'next/head'
import { useRouter } from 'next/router'

export default function Home() {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>Spotifive</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          display: `flex`,
          width: `100%`,
          height: `100vh`,
          justifyContent: `center`,
          alignItems: `center`,
        }}
      >
        <Button
          variant="contained"
          size="large"
          color="success"
          onClick={() => {
            router.push({
              pathname: `https://accounts.spotify.com/authorize`,
              query: {
                client_id: `28c510628cfa4d06af9b8b6803186dd8`,
                redirect_uri: `${process.env.NEXT_PUBLIC_URL}/home`,
                response_type: `token`,
                scope: `user-top-read user-read-private`,
              },
            })
          }}
        >
          Log in with Spotify
        </Button>
      </Box>
    </>
  )
}
